version: '3'
services:

  bot:
    image: "incarcerous8/receiptbotimage:prod"
    container_name: "receiptbot_container"
    env_file:
      - dbot.env
    restart: always
    networks:
      - botnetwork
    ports:
      - "8095:8095"
    depends_on:
      - recognition

  recognition:
    image: "incarcerous8/receiptrecognimage:prod"
    container_name: "receiptrecogn_container"
    env_file:
      - dbot.env
    restart: always
    networks:
      - botnetwork
    ports:
      - "8097:8097"

networks:
  localhost:
    driver: bridge
