version: '3'
services:

  receiptbot:
    #    image: "incarcerous8/receiptbot:prod"  # For prod environment
    container_name: "receiptbot_container"  # For non-prod environment
    build: ./bot  # For non-prod environment
    environment:
      - MONGO_URL=mongodb://db:27017/
    env_file:
      - dbot.env
    restart: always
    networks:
      - db_nw
    ports:
      - "8095:8095"
    depends_on:
      - db

  db:
    image: "mongo:4.0.18"
    container_name: "mongodb_container"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    #      - MONGODB_USER="user"
    #      - MONGODB_PASS="pass"
    volumes:
      - "~/receiptsbot/db:/data/db"
    #    env_file:
    #      - db.env
    restart: always
    networks:
      - db_nw
    command: mongod --smallfiles --logpath=/dev/null # --quiet

networks:
  db_nw:
    driver: bridge
