version: '3'
services:

  receiptbot:
    container_name: "receiptbot_bot_container"
    #    image: "incarcerous8/receiptbot:prod"  # For prod environment
    build: ./bot  # For non-prod environment
    env_file:
      - bot.env
    restart: always
    networks:
      - db_nw
    ports:
      - "8095:8095"
    depends_on:
      - db

  db:
    image: "postgres:12"
    container_name: "receiptbot_db_container"
    volumes:
      - "~/receiptbot/db:/var/lib/postgresql/data"
    env_file:
      - bot.env
    restart: always
    networks:
      - db_nw

networks:
  db_nw:
    driver: bridge
