version: '3'
services:

  receiptbot:
    #    image: "incarcerous8/receiptbot:prod"  # For prod environment
    container_name: "receiptbot_container"  # For non-prod environment
    build: ./bot  # For non-prod environment
    environment:
      - MONGO_URL=mongodb://db:27017/
    env_file:
      - dbot.env
    restart: always
    networks:
      - db_nw
    ports:
      - "8095:8095"
    depends_on:
      - db

  db:
    image: "postgres:12"
    container_name: "postgres_container"
    environment:
    volumes:
      - "~/receiptbot/db:/var/lib/postgresql/data"
    env_file:
      - dbot.env
    restart: always
    networks:
      - db_nw

networks:
  db_nw:
    driver: bridge
