version: '3'
services:

  bot:
    image: "incarcerous8/receiptbotimage:prod"
    container_name: "receiptbot_container"
    env_file:
      - dbot.env
    restart: always
    networks:
      - botnetwork
    ports:
      - "8095:8095"
    depends_on:
      - calculator
      - recognition

  calculator:
    image: "incarcerous8/receiptcalcimage:prod"
    container_name: "receiptcalc_container"
    env_file:
      - dbot.env
    restart: always
    networks:
      - botnetwork
    ports:
      - "8096:8096"

  recognition:
    image: "incarcerous8/receiptrecognimage:prod"
    container_name: "receiptrecogn_container"
    env_file:
      - dbot.env
    restart: always
    networks:
      - botnetwork
    ports:
      - "8097:8097"

networks:
  localhost:
    driver: bridge
