bot:
  token: ${BOT_TOKEN}
  username: ${BOT_USERNAME}  # without "@"

spring:
  banner:
    location: 'classpath:/static/banner'
  main:
    allow-bean-definition-overriding: true
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://db:5432/postgres
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

#logging:
#  level:
#    root: debug
