bot:
  token: ${BOT_TOKEN}
  username: ${BOT_USERNAME}  # without "@"

spring:
  banner:
    location: 'classpath:/static/banner'
  main:
    allow-bean-definition-overriding: true

#logging:
#  level:
#    root: debug
